-- Yours Mart production schema. PostgreSQL is recommended for deployment.
CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY, full_name VARCHAR(120) NOT NULL, email VARCHAR(180) UNIQUE NOT NULL,
  username VARCHAR(80) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS categories (id BIGSERIAL PRIMARY KEY, name VARCHAR(120) UNIQUE NOT NULL, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS products (
  id BIGSERIAL PRIMARY KEY, name VARCHAR(180) NOT NULL, slug VARCHAR(220) UNIQUE NOT NULL, brand VARCHAR(120),
  category VARCHAR(120) NOT NULL, description TEXT, price NUMERIC(12,2) NOT NULL, original_price NUMERIC(12,2),
  discount NUMERIC(5,2) DEFAULT 0, stock INTEGER DEFAULT 0, sizes TEXT, colors TEXT, rating NUMERIC(3,2) DEFAULT 0,
  review_count INTEGER DEFAULT 0, tags TEXT, image_url TEXT NOT NULL, additional_images TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS cart_items (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL,product_id BIGINT NOT NULL,quantity INTEGER NOT NULL,size VARCHAR(30),color VARCHAR(50),UNIQUE(user_id,product_id,size,color));
CREATE TABLE IF NOT EXISTS wishlist (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL,product_id BIGINT NOT NULL,UNIQUE(user_id,product_id));
CREATE TABLE IF NOT EXISTS addresses (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL,full_name VARCHAR(120),phone VARCHAR(40),address TEXT,city VARCHAR(80),postal_code VARCHAR(30),instructions TEXT);
CREATE TABLE IF NOT EXISTS orders (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL,total NUMERIC(12,2) NOT NULL,shipping_address TEXT NOT NULL,payment_method VARCHAR(40) DEFAULT 'COD',payment_status VARCHAR(40) DEFAULT 'Pending',status VARCHAR(40) DEFAULT 'Pending',created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items (id BIGSERIAL PRIMARY KEY,order_id BIGINT NOT NULL,product_id BIGINT NOT NULL,quantity INTEGER NOT NULL,price NUMERIC(12,2) NOT NULL,size VARCHAR(30),color VARCHAR(50));
CREATE TABLE IF NOT EXISTS tryon_history (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL,product_id BIGINT NOT NULL,job_id VARCHAR(255),status VARCHAR(40),result_url TEXT,created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
